### PR TITLE
add optional domains scope attribute

### PR DESCRIPTION
**Pull request by Falibur**
Pass in optional domains array for mailcheck to check email address

### CODE REVIEW

**Comment by simison** [comment]
Great!

@Falibur what would you think about just passing options object to this directive? It would allow sending these domains and any other settings Mailcheck has/might have in the future.

See https://github.com/simison/angular-mailcheck/issues/4#issuecomment-273890233

**Comment by Falibur** [comment]
Sounds as an even better approach!

When I do have the time I will update the code

**Comment by simison** [comment]
@Falibur that would be awesome!

**Comment by simison** [comment]
@Falibur any news on this? No worries if you don't have time — I'll eventually just get into this myself then. :-)

**Comment by simison** [comment]
Added feature to pass Mailcheck options object:

https://github.com/simison/angular-mailcheck/commit/408acdf299549115afdb6617ccf1c09e5f6136bb

**Pull request closed without merging**
